<a href="https://colab.research.google.com/github/monishabhojkumar12-avi/final-project/blob/main/LSTM_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

merged_df = pd.read_csv("merged_browser_ram.csv")

In [2]:
merged_df.head(10)

,timestamp,url,domain,category,browser,ram_used_mb,ram_available_mb,browser_ram_mb,time_diff,new_session,session_id,hour
0,2026-02-01 00:00:36,https://x.com/page74,x.com,social,chrome,7297.078805,8702.921195,634.550154,NaN,0,0,0
1,2026-02-01 00:02:08,https://stackoverflow.com/page13,stackoverflow.com,learning,chrome,5996.921381,10003.078619,891.922551,1.533333,0,0,0
2,2026-02-01 00:03:14,https://github.com/page3,github.com,learning,chrome,6538.321890,9461.678110,1183.595947,1.100000,0,0,0
3,2026-02-01 00:04:53,https://youtube.com/page5,youtube.com,video,chrome,7900.443030,8099.556970,632.466125,1.650000,0,0,0
4,2026-02-01 00:05:56,https://facebook.com/page68,facebook.com,social,chrome,7038.437277,8961.562723,1012.808236,1.050000,0,0,0
5,2026-02-01 00:07:50,https://medium.com/page1,medium.com,learning,chrome,5844.427020,10155.572980,437.512376,1.900000,0,0,0
6,2026-02-01 00:09:39,https://youtube.com/page82,youtube.com,video,chrome,6334.918075,9665.081925,849.381720,1.816667,0,0,0
7,2026-02-01 00:10:14,https://medium.com/page56,medium.com,learning,edge,6908.885896,9091.114104,706.713030,0.583333,0,0,0
8,2026-02-01 00:10:37,https://medium.com/page15,medium.com,learning,edge,7045.177703,8954.822297,1593.516061,0.383333,0,0,0
9,2026-02-01 01:02:37,https://stackoverflow.com/page82,stackoverflow.com,learning,edge,7044.839886,8955.160114,803.361231,52.000000,1,1,1


In [3]:
from sklearn.preprocessing import LabelEncoder

# Use merged_df (event-level data)
df = merged_df.copy()

# Encode categories
le = LabelEncoder()
df['category_encoded'] = le.fit_transform(df['category'])

# Sort by time
df = df.sort_values('timestamp')

# Create sequences
sequence_length = 5

X = []
y = []

categories = df['category_encoded'].values

for i in range(len(categories) - sequence_length):
    X.append(categories[i:i+sequence_length])
    y.append(categories[i+sequence_length])

import numpy as np
X = np.array(X)
y = np.array(y)

In [4]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding

num_classes = len(le.classes_)

model = Sequential([
    Embedding(input_dim=num_classes, output_dim=8, input_length=sequence_length),
    LSTM(64),
    Dense(32, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.2)

Epoch 1/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.3152 - loss: 1.4908 - val_accuracy: 0.3097 - val_loss: 1.4929
Epoch 2/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.3155 - loss: 1.4876 - val_accuracy: 0.3097 - val_loss: 1.4940
Epoch 3/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 19s 16ms/step - accuracy: 0.3155 - loss: 1.4870 - val_accuracy: 0.3097 - val_loss: 1.4931
Epoch 4/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 19s 19ms/step - accuracy: 0.3155 - loss: 1.4871 - val_accuracy: 0.3097 - val_loss: 1.4932
Epoch 5/5
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.3155 - loss: 1.4869 - val_accuracy: 0.3097 - val_loss: 1.4926


In [16]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score,f1_score

y_pred = model.predict(X_test).argmax(axis=1)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nF1 Score:", f1_score(y_test, y_pred, average='weighted'))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy:", accuracy_score(y_test, y_pred))

most_common = np.bincount(y_train).argmax()
y_baseline = np.full_like(y_test, most_common)

baseline_acc = accuracy_score(y_test, y_baseline)
baseline_f1 = f1_score(y_test, y_baseline, average='macro')
print("\n=== BASELINE ===")
print("Baseline Accuracy:", baseline_acc)
print("Baseline Macro F1:", baseline_f1)
print("\n================")


625/625 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step
Confusion Matrix:
[[6324    0    0    0    0]
 [1289    0    0    0    0]
 [2532    0    0    0    0]
 [4965    0    0    0    0]
 [4889    0    0    0    0]]

Accuracy: 0.3162158107905395

F1 Score: 0.15193927648363578

Classification Report:
              precision    recall  f1-score   support

           0       0.32      1.00      0.48      6324
           1       0.00      0.00      0.00      1289
           2       0.00      0.00      0.00      2532
           3       0.00      0.00      0.00      4965
           4       0.00      0.00      0.00      4889

    accuracy                           0.32     19999
   macro avg       0.06      0.20      0.10     19999
weighted avg       0.10      0.32      0.15     19999


Accuracy: 0.3162158107905395

=== BASELINE ===
Baseline Accuracy: 0.3162158107905395
Baseline Macro F1: 0.09609846901948867



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [17]:

loss, acc = model.evaluate(X_test, y_test)
print("Accuracy:", acc)

625/625 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.3162 - loss: 1.4929
Accuracy: 0.3162158131599426


In [27]:
import pickle
model.save("lstm_model.h5")
pickle.dump(le, open("label_encoder.pkl", "wb"))

**Autoencoder**

In [18]:

session_df = pd.read_csv("session_features.csv")

In [19]:
from sklearn.preprocessing import StandardScaler

features = session_df[[
    'session_duration',
    'num_events',
    'avg_browser_ram',
    'peak_browser_ram'
]]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(features)

In [20]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

input_dim = X_scaled.shape[1]

input_layer = Input(shape=(input_dim,))

encoded = Dense(8, activation='relu')(input_layer)
encoded = Dense(4, activation='relu')(encoded)

decoded = Dense(8, activation='relu')(encoded)
decoded = Dense(input_dim, activation='linear')(decoded)

autoencoder = Model(inputs=input_layer, outputs=decoded)

autoencoder.compile(optimizer='adam', loss='mse')

autoencoder.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 4)              │            36 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 152 (608.00 B)

 Trainable params: 152 (608.00 B)

 Non-trainable params: 0 (0.00 B)

In [21]:
autoencoder.fit(
    X_scaled, X_scaled,
    epochs=20,
    batch_size=32,
    validation_split=0.1
)

Epoch 1/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.9062 - val_loss: 0.7172
Epoch 2/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6122 - val_loss: 0.3981
Epoch 3/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1927 - val_loss: 0.0727
Epoch 4/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0524 - val_loss: 0.0416
Epoch 5/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0368 - val_loss: 0.0327
Epoch 6/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0299 - val_loss: 0.0273
Epoch 7/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0254 - val_loss: 0.0235
Epoch 8/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0224 - val_loss: 0.0208
Epoch 9/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0187 - val_loss: 0.0166
Epoch 10/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0157 - val_loss: 0.0143
Epoch 11/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0136 - val_loss: 0.0124
Epoch 12/20
139/139 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [22]:
reconstructions = autoencoder.predict(X_scaled)

mse = np.mean(np.power(X_scaled - reconstructions, 2), axis=1)

session_df['reconstruction_error'] = mse

# Threshold (top 5% as anomalies)
threshold = np.percentile(mse, 95)

session_df['anomaly'] = session_df['reconstruction_error'] > threshold

155/155 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [23]:

anomalies = session_df[session_df['anomaly'] == True]

print(anomalies[['session_id','session_duration','peak_browser_ram']].head())

     session_id  session_duration  peak_browser_ram
15           15         39.266667       1968.290850
23           23         63.733333       1978.978373
72           72         41.583333       1622.282574
86           86        112.733333       1936.754127
100         100         28.500000       1980.402968


In [24]:

anomalies = session_df[session_df['anomaly'] == True]

print(anomalies[['session_id','session_duration','peak_browser_ram']].head())

     session_id  session_duration  peak_browser_ram
15           15         39.266667       1968.290850
23           23         63.733333       1978.978373
72           72         41.583333       1622.282574
86           86        112.733333       1936.754127
100         100         28.500000       1980.402968


In [25]:

import joblib

joblib.dump(le, "label_encoder.pkl")

['label_encoder.pkl']

In [26]:
autoencoder.save("autoencoder_model.h5")
joblib.dump(scaler, "autoencoder_scaler.pkl")

['autoencoder_scaler.pkl']

**streamlit**

In [36]:
!pip install -q streamlit
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
import subprocess
subprocess.Popen(["./cloudflared-linux-amd64", "tunnel", "--url", "http://localhost:8501"])
!nohup /content/cloudflared-linux-amd64 tunnel --url http://localhost:8501 &

--2026-05-06 04:50:13--  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64 [following]
--2026-05-06 04:50:13--  https://github.com/cloudflare/cloudflared/releases/download/2026.3.0/cloudflared-linux-amd64
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://release-assets.githubusercontent.com/github-production-release-asset/106867604/731ab2f8-6b77-4adb-a7b3-1104525e9d72?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-05-06T05%3A23%3A42Z&rscd=attachment%3B+filename%3Dcloudflared-linux-amd64&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-05-06T0

In [41]:
%%writefile app.py
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

st.set_page_config(page_title="Browsing Behavior Analyzer", layout="wide")

# ---------------------------
# LOAD DATA
# ---------------------------
@st.cache_data
def load_data():
    merged = pd.read_csv("merged_browser_ram.csv")
    session = pd.read_csv("session_features.csv")

    merged['timestamp'] = pd.to_datetime(merged['timestamp'])
    session['start_time'] = pd.to_datetime(session['start_time'])
    session['end_time'] = pd.to_datetime(session['end_time'])

    return merged, session

merged_df, session_df = load_data()

# ---------------------------
# LOAD MODELS
# ---------------------------
@st.cache_resource
def load_models():
    kmeans = joblib.load("kmeans_model.pkl")
    scaler = joblib.load("scaler.pkl")

    lstm_model = load_model("lstm_model.h5",compile=False)
    le = joblib.load("label_encoder.pkl")

    autoencoder = load_model("autoencoder_model.h5",compile=False)
    ae_scaler = joblib.load("autoencoder_scaler.pkl")

    return kmeans, scaler, lstm_model, le, autoencoder, ae_scaler

kmeans, scaler, lstm_model, le, autoencoder, ae_scaler = load_models()

# ---------------------------
# TITLE
# ---------------------------
st.title("🧠 Time-Based Browsing Pattern Analyzer")
st.markdown("Analyze user browsing behavior, system RAM usage, and generate intelligent insights.")

# ---------------------------
# SIDEBAR FILTER
# ---------------------------
st.sidebar.header("Filter")

days = st.sidebar.selectbox("Select Time Window", ["All", "3 Days", "5 Days"])

if days != "All":
    n = int(days.split()[0])
    cutoff = merged_df['timestamp'].max() - pd.Timedelta(days=n)
    merged_df = merged_df[merged_df['timestamp'] >= cutoff]

# ---------------------------
# OVERVIEW
# ---------------------------
st.header("📊 Overview")

col1, col2, col3 = st.columns(3)

col1.metric("Total Events", len(merged_df))
col2.metric("Total Sessions", session_df['session_id'].nunique())
col3.metric("Avg Session Duration (min)", round(session_df['session_duration'].mean(), 2))

# ---------------------------
# CATEGORY ANALYSIS
# ---------------------------
st.header("🌐 Category Distribution")

cat_counts = merged_df['category'].value_counts()

fig, ax = plt.subplots()
cat_counts.plot(kind='bar', ax=ax)
st.pyplot(fig)

st.markdown("""
**Insight:**
This chart shows dominant user activity categories such as social, video, or learning.
It helps identify where most time is spent.
""")

# ---------------------------
# TIME ANALYSIS
# ---------------------------
st.header("⏰ Time-Based Usage")

merged_df['hour'] = merged_df['timestamp'].dt.hour
hour_counts = merged_df.groupby('hour').size()

fig, ax = plt.subplots()
hour_counts.plot(kind='bar', ax=ax)
st.pyplot(fig)

st.markdown("""
**Insight:**
Peak browsing hours highlight productivity or distraction patterns.
""")

# ---------------------------
# RAM ANALYSIS
# ---------------------------
st.header("💻 RAM Usage by Category")

ram_usage = merged_df.groupby('category')['browser_ram_mb'].mean().sort_values()

fig, ax = plt.subplots()
ram_usage.plot(kind='barh', ax=ax)
st.pyplot(fig)

st.markdown("""
**Insight:**
Categories with higher RAM usage (e.g., video) impact system performance significantly.
""")

# ---------------------------
# CLUSTER ANALYSIS
# ---------------------------
st.header("🔍 Session Clustering")

cluster_summary = session_df.groupby('cluster')[[
    'session_duration',
    'num_events',
    'avg_browser_ram'
]].mean()

st.dataframe(cluster_summary)

st.markdown("""
**Explanation:**
Clustering groups sessions into behavior types:
- Short sessions → casual browsing
- Long sessions → binge or focused usage
- High RAM sessions → heavy applications

This helps identify user behavior patterns.
""")

# ---------------------------
# ANOMALY DETECTION
# ---------------------------
st.header("🚨 Anomaly Detection")

if 'anomaly' in session_df.columns:
    anomalies = session_df[session_df['anomaly'] == True]
    st.write("Total anomalies:", len(anomalies))
    st.dataframe(anomalies.head(10))

    st.markdown("""
    **Explanation:**
    Anomalies represent unusual sessions such as:
    - Extremely long sessions
    - High RAM spikes
    - Irregular browsing behavior
    """)
else:
    st.warning("Run autoencoder to detect anomalies.")

# ---------------------------
# PREDICTION SECTION
# ---------------------------
st.header("🔮 Predict User Behavior")

col1, col2 = st.columns(2)

with col1:
    duration = st.number_input("Session Duration (min)", value=30)
    events = st.number_input("Number of Events", value=10)
    avg_ram = st.number_input("Avg RAM", value=800)
    peak_ram = st.number_input("Peak RAM", value=1200)


    seq_input = st.text_input("Last 5 categories (comma separated)",
                             "social,video,learning,social,video")

analyze = st.button("Analyze")

if analyze:

    session_input = [duration, events, avg_ram, peak_ram]

    # ---- Cluster ----
    scaled = scaler.transform([session_input])
    cluster = kmeans.predict(scaled)[0]

    # ---- LSTM ----
    seq = [s.strip() for s in seq_input.split(",")]

    try:
        encoded = [le.transform([c])[0] for c in seq]
    except:
        st.error("Invalid category entered")
        st.stop()

    pred = lstm_model.predict(np.array([encoded]))
    next_cat = le.inverse_transform([np.argmax(pred)])[0]

    # ---- Autoencoder ----
    scaled_ae = ae_scaler.transform([session_input])
    recon = autoencoder.predict(scaled_ae)

    error = np.mean((scaled_ae - recon) ** 2)

    threshold = 0.05
    anomaly = error > threshold

    # ---- Recommendations ----
    recs = []

    if peak_ram > 1200:
        recs.append("⚠️ High RAM usage → close unused tabs")

    if duration > 60:
        recs.append("⏳ Long session → take breaks")

    if events > 30:
        recs.append("🔁 Too many events → reduce multitasking")

    if next_cat == "social":
        recs.append("📱 Social usage predicted → avoid distractions")

    if anomaly:
        recs.append("🚨 Unusual session detected")

    if not recs:
        recs.append("✅ Usage looks healthy")

    # ---- Output ----
    st.subheader("Results")

    st.write("Cluster:", cluster)
    st.write("Next Category:", next_cat)
    st.write("Anomaly:", anomaly)

    st.subheader("📌 Recommendations")

    for r in recs:
        st.success(r)

    # DEBUG
    st.write("DEBUG:", error)

Overwriting app.py


In [42]:
!streamlit run /content/model.py &>/content/logs.txt &

In [43]:
!grep -o 'https://.*\.trycloudflare.com' nohup.out | head -n 1 | xargs -I {} echo "Your tunnel url {}"

Your tunnel url https://limit-configuring-bandwidth-rich.trycloudflare.com
